site_name: Community Created Maps of India
site_description: A project website for maps of Indian Assembly Constituencies; Parliamentary constituencies; States; Districts and Village boundaries in geojson and shape file format for download and reuse. 
theme_dir: cinder
pages:
    - Home: index.md
    - Contributing: contributing.md
    - Reference: reference.md
    - Tools: tools.md
    - Maps:
      - 'Assembly Constituencies': 'assembly-constituencies/index.md'
      - 'Parliamentary constituencies': 'parliamentary-constituencies/index.md'
      - 'States': 'states/index.md'
      - 'Districts': 'districts/index.md'
      - 'Spatial data of Municipalities': 'Municipal_Spatial_Data.md'
      - 'India Village Boundaries(Maps)': 'indian_village_boundaries.md'
site_dir: './../docs'
extra_css:
    - 'bower_components/leaflet/dist/leaflet.css'
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/d3/3.3.0/d3.min.js'
    - 'bower_components/leaflet/dist/leaflet.js'
    - 'js/mapsplot.js'